/** New form for the runtime. */
export default async function (ctx: Context, _session: Session | null, _opts: {}): Promise<string> {
    const esc = (s: any) => ctx.fns.procs.ui.escape({ text: s });
    const last = ((await ctx.fns.procs.db.select({ sql: "SELECT value FROM kv WHERE key = 'last-model'" }).catch(() => [])) as any[])[0]?.value;
    const model = last ?? (await ctx.fns.settings.modelDefault({})) ?? ctx.env.MODEL ?? '';
    const groups = await ctx.fns.llm.listModels({});
    const base = await ctx.fns.agent.getBasePromptParts({});
    const presets = await ctx.fns.agent.listPromptPresets({});
    const options = Object.entries(groups).map(([provider, ids]) => `<optgroup label="${esc(provider)}">${(ids as string[]).map(id => `<option value="${esc(id)}" ${id === model ? 'selected' : ''}>${esc(id)}</option>`).join('')}</optgroup>`).join('');
    const presetHtml = Object.entries(presets).map(([id, p]: any) => `<details class="rounded-md border border-base-300 bg-base-100"><summary class="cursor-pointer px-3 py-2"><label class="flex gap-2 text-sm"><input type="checkbox" name="promptPreset" value="${esc(id)}"><span>${esc(p.label)} <span class="text-faint">${Math.ceil((p.text?.length || 0) / 4)}t</span></span></label></summary><pre class="border-t border-base-300 bg-base-200 p-3 text-2xs whitespace-pre-wrap">${esc(p.text)}</pre></details>`).join('');
    return `<input name="title" maxlength="120" placeholder="title (optional)" class="input input-bordered w-full bg-base-100"><select name="model" class="select select-bordered w-full bg-base-100 font-mono">${options}</select><div class="relative"><input id="workspace-dir-input" name="workspaceDir" value="${esc(process.cwd())}" required autocomplete="off" aria-autocomplete="list" aria-controls="workspace-dir-suggestions" hx-get="/agent/dirs" hx-trigger="focus, input changed delay:250ms" hx-target="#workspace-dir-suggestions" hx-swap="innerHTML" hx-on::before:swap="if(event.detail.ctx?.target?.id==='workspace-dir-suggestions'&&!this.matches(':focus')&&!document.getElementById('workspace-dir-suggestions').matches(':focus-within'))event.preventDefault()" class="input input-bordered w-full bg-base-100 font-mono"><div id="workspace-dir-suggestions" role="listbox" aria-label="Workspace folders" class="absolute z-50 mt-1 w-full overflow-hidden rounded-box border border-base-300 bg-base-100 shadow-lg empty:hidden"></div><script>(function(){var i=document.getElementById("workspace-dir-input"),l=document.getElementById("workspace-dir-suggestions");if(!i||!l||l.dataset.wired)return;l.dataset.wired="1";var close=function(){l.replaceChildren()};var outside=function(e){if(!i.contains(e.target)&&!l.contains(e.target))close()};["pointerdown","click","focusin"].forEach(function(t){document.addEventListener(t,outside,true)});document.addEventListener("keydown",function(e){if(e.key==="Escape")close()},true)})()</script><div id="workspace-dir-status" class="mt-1 min-h-5 text-2xs" hx-get="/agent/dirs/status" hx-trigger="load" hx-include="#workspace-dir-input"></div></div><details class="rounded border border-base-300"><summary class="p-2">Base system prompt · ${Math.ceil((base.core?.length || 0) / 4)}t</summary><pre class="border-t border-base-300 bg-base-200 p-3 text-2xs whitespace-pre-wrap">${esc(base.core)}</pre></details>${presetHtml}<textarea name="systemPrompt" rows="4" placeholder="custom instructions (optional)" class="textarea textarea-bordered w-full bg-base-100 font-mono"></textarea>`;
}
