import {test,expect} from 'bun:test';
const raw=async(path:string)=>(await import(path)).default;
async function fixture(){let calls=0;let rows:any[]=[];let fail=false;const events:any[]=[];const ctx:any={state:{flow:{declarations:{}}},fns:{flow:{list:async()=>{calls++;await Bun.sleep(2);if(fail)throw Error('offline');return rows;}},procs:{events:{emit:({event}:any)=>events.push(event)}}}};const refresh=await raw('./src/flow/refreshCount.ts');ctx.fns.flow.refreshCount=(opts:any)=>refresh(ctx,null,opts);return {ctx,events,run:ctx.fns.flow.refreshCount,rows:(v:any[])=>rows=v,fail:()=>fail=true,calls:()=>calls};}
const row=(n:number,error?:string)=>({result:{gaps:Array(n).fill({}),error,status:error?'failed':'preview'}});
test('zero, aggregate count, concurrent single flight and five minute TTL',async()=>{const f=await fixture();expect((await f.run({})).count).toBe(0);f.rows([row(2),row(3)]);expect((await f.run({})).count).toBe(0);f.ctx.state.flow.countCache.attemptedAt-=300001;const results=await Promise.all(Array.from({length:8},()=>f.run({})));expect(results.every(r=>r.count===5)).toBe(true);expect(f.calls()).toBe(2);expect(f.events).toHaveLength(2);});
test('partial and total failures retain last complete count, no false zero',async()=>{const f=await fixture();f.rows([row(4)]);await f.run({});f.rows([row(0),row(0,'unavailable')]);const partial=await f.run({force:true});expect(partial.count).toBe(4);expect(partial.partial).toBe(true);expect(partial.stale).toBe(true);f.fail();expect(await f.run({force:true})).toMatchObject({count:4,stale:true});});
test('uninitialized failures remain unknown',async()=>{const f=await fixture();f.rows([row(1,'error')]);expect(await f.run({})).toMatchObject({count:null,checkedAt:null,stale:true,partial:true});});
test('badge accessible, circular, hides zero/unknown/optional plugin and marks stale',async()=>{const badge=await raw('../../src/ui/gapBadge.ts');const f=await fixture();expect(await badge(f.ctx,null,{})).toContain(' hidden');f.rows([row(3)]);await f.run({});const html=await badge(f.ctx,null,{});expect(html).toContain('href="/gaps"');expect(html).toContain('aria-label="3 active gaps"');expect(html).toContain('rounded-full');expect(html).not.toContain(' hidden');f.ctx.state.flow.countCache.stale=true;expect(await badge(f.ctx,null,{})).toContain('stale; last complete check');expect(await badge({state:f.ctx.state,fns:{}},null,{})).toContain(' hidden');f.ctx.state.flow.countCache.count=0;expect(await badge(f.ctx,null,{})).toContain(' hidden');});
test('declaration reload preserves cache identity and cron is five minutes',async()=>{const loader=await raw('./src/flow/$loader_gap.ts');const f=await fixture();await f.run({});const state=f.ctx.state.flow;await loader(f.ctx,null,{entries:[]});expect(f.ctx.state.flow).toBe(state);expect(state.countCache.count).toBe(0);const cron=await raw('./src/flow/$cron_flow-count.ts');expect(cron).toMatchObject({every:'5m',now:true,fn:'flow.refreshCount'});});
