import {test,expect} from 'bun:test';
// Tests load raw procedures dynamically; production procedures use ctx.fns exclusively.
const raw=async(name:string)=>(await import(`./src/flow/${name}.ts`)).default;
async function fixture(kind='close') {
 const receipts=new Map<string,any>();let calls=0,reads=0,closed=false;
 const ctx:any={state:{flow:{declarations:{}}},fns:{flow:{},procs:{db:{run:async({sql,params}:any)=>{if(sql.startsWith('INSERT'))receipts.set(params[0],JSON.parse(params[2]));else receipts.set(params[1],JSON.parse(params[0]));}}}}};
 ctx.fns.procs.ui={};for(const n of ['escape','attr','field','button']){const fn=(await import(`../../src/procs/ui/${n}.ts`)).default;ctx.fns.procs.ui[n]=(o:any)=>fn(ctx,null,o);}for(const name of ['discover','reconcile','list','page','formField','card']){const fn=await raw(name);ctx.fns.flow[name]=(opts:any)=>fn(ctx,null,opts);}
 ctx.fns.flow.refresh=async()=>{};
 const gap={id:'need:1',revision:'r1',summary:'Incomplete <script>',will:'Complete'};
 ctx.fns.flow.refreshCount=async()=>({count:0,stale:false});
 ctx.state.flow.declarations.check={name:'check',source:'synthetic',fn:async(_ctx:any,_s:any,opts:any)=>{if(opts.mode==='preview'){reads++;if(kind==='discoverError'||(kind==='verifyError'&&calls))throw new Error('discovery failed');return {gaps:closed?[]:[gap]};}calls++;if(kind==='actionError')throw new Error('action failed');if(kind==='close')closed=true;return {effects:[{reference:'synthetic:1'}]};}};
 return {ctx,receipts,gap,stats:()=>({calls,reads})};
}
const apply={flow:'check',mode:'apply',target:{id:'need:1',revision:'r1'}};
test('preview and explain are read-only and persist no receipts',async()=>{const f=await fixture();expect((await f.ctx.fns.flow.reconcile({flow:'check',mode:'preview'})).gaps).toHaveLength(1);expect((await f.ctx.fns.flow.reconcile({...apply,mode:'explain'})).status).toBe('explained');expect(f.stats().calls).toBe(0);expect(f.receipts.size).toBe(0);});
test('fresh recheck rejects stale/missing revision without action',async()=>{const f=await fixture();for(const target of [{id:'need:1',revision:'old'},{id:'absent',revision:'r1'}])expect((await f.ctx.fns.flow.reconcile({...apply,target})).status).toBe('stale');await expect(f.ctx.fns.flow.reconcile({...apply,target:{id:'need:1'}})).rejects.toThrow('revision');expect(f.stats().calls).toBe(0);expect(f.receipts.size).toBe(2);});
test('apply verifies closure and durable receipt',async()=>{const f=await fixture();const r=await f.ctx.fns.flow.reconcile(apply);expect(r.status).toBe('closed');expect(r.verified).toBe(true);expect(r.converged).toBe(true);expect(f.stats()).toEqual({calls:1,reads:2});expect(f.receipts.get(r.id)).toEqual(r);});
test('effect success does not mean need closed',async()=>{const f=await fixture('remind');const r=await f.ctx.fns.flow.reconcile(apply);expect(r.status).toBe('remains');expect(r.effects).toHaveLength(1);expect(r.converged).toBe(false);});
test('discover, action and verify failures produce honest receipts',async()=>{for(const kind of ['discoverError','actionError','verifyError']){const f=await fixture(kind);const r=await f.ctx.fns.flow.reconcile(apply);expect(r.status).toBe('failed');expect(r.verified).toBe(false);expect(r.actionCalled).toBe(kind!=='discoverError');expect(f.receipts.get(r.id).error).toBeTruthy();}});
test('receipt reservation failure prevents action',async()=>{const f=await fixture();f.ctx.fns.procs.db.run=async()=>{throw new Error('db down');};await expect(f.ctx.fns.flow.reconcile(apply)).rejects.toThrow('db down');expect(f.stats().calls).toBe(0);});
test('invalid and duplicate gaps rejected; informational gaps cannot apply',async()=>{const f=await fixture();f.ctx.state.flow.declarations.check.fn=async()=>({gaps:[f.gap,f.gap]});expect((await f.ctx.fns.flow.reconcile({flow:'check',mode:'preview'})).error).toContain('Duplicate');delete (f.gap as any).will;f.ctx.state.flow.declarations.check.fn=async()=>({gaps:[f.gap]});expect((await f.ctx.fns.flow.reconcile(apply)).error).toContain('no available action');});
test('loader uses later-root override, refreshes removed declarations, rejects scheduler objects',async()=>{const load=await raw('$loader_gap');const ctx:any={state:{}};const a=async()=>({gaps:[]}),b=async()=>({gaps:[]});await load(ctx,null,{entries:[{name:'check',rel:'src/$gap_check.ts',abs:'src',fn:a},{name:'check',rel:'.hyper/$gap_check.ts',abs:'.hyper',fn:b}]});expect(ctx.state.flow.declarations.check.fn).toBe(b);await load(ctx,null,{entries:[]});expect(Object.keys(ctx.state.flow.declarations)).toHaveLength(0);await load(ctx,null,{entries:[{name:'check',rel:'bad',fn:{entry:'step'}}]});await expect(ctx.state.flow.declarations.check.fn()).rejects.toThrow('function');});
test('page isolates failed checks, escapes content, sends target revision, honest empty state',async()=>{const f=await fixture();f.ctx.state.flow.declarations.broken={name:'broken',source:'bad',fn:async()=>{throw new Error('broken check');}};let page=await f.ctx.fns.flow.page({});expect(page).toContain('>Gaps</h1>');expect(page).toContain('&lt;script&gt;');expect(page).toContain('broken check');expect(page).toContain('name="revision" value="r1"');f.ctx.state.flow.declarations={};page=await f.ctx.fns.flow.page({});expect(page).toContain('Правила ещё не подключены');expect(page).toContain('radial-gradient');expect(page).not.toContain('<section');});
test('GET returns shared Hyper layout contract, not JSON body or a standalone document',async()=>{const f=await fixture();const get=(await import('./src/gaps/$route__GET.ts')).default;const r=await get(f.ctx,null,{req:new Request('http://local/gaps'),params:{}});expect(Object.keys(r).sort()).toEqual(['main','title']);expect(r.main).toContain('id="gaps-page"');expect(r.main).not.toContain('<html');expect(f.stats().calls).toBe(0);expect(f.receipts.size).toBe(0);});
test('POST refuses cross-origin and rechecks valid submission then refreshes list',async()=>{const f=await fixture();const route=(await import('./src/gaps/$route_apply_POST.ts')).default;expect((await route(f.ctx,null,{req:new Request('http://local/gaps/apply',{method:'POST',headers:{origin:'http://evil'}}),params:{}}) as Response).status).toBe(403);const r:any=await route(f.ctx,null,{req:new Request('http://local/gaps/apply',{method:'POST',headers:{origin:'http://local'},body:new URLSearchParams({flow:'check',id:'need:1',revision:'r1'})}),params:{}});expect(r.main).toContain('closed; receipt');expect(r.main).toContain('Сейчас нет открытых gaps');expect(r.body).toBeUndefined();expect(r.title).toBe('Gaps');});
