/**
 * Renders the shared context-agent registry and task controls
 *
 * Builds the Shared Agents application page with publishing controls, discoverable capability cards, task delegation forms, and recent task results. Use from the Shared Agents HTTP page route.
 * @param opts.currentAgentId Optional agent session preselected for publishing and recorded as requester.
 * @param opts.selectedAgentId Optional published agent highlighted from navigation.
 */
export default async function (
    ctx: Context,
    session: Session | null,
    opts: {
        /** Optional agent session preselected for publishing and recorded as requester. */
        currentAgentId?: string;
        /** Optional published agent highlighted from navigation. */
        selectedAgentId?: string;
    },
): Promise<string> {
    const esc = (value: any) => ctx.fns.procs.ui.escape({ text: String(value ?? "") });
    const agents = await ctx.fns.session.list({});
    const cards = await ctx.fns.sharedAgent.list({});
    const selected = String(opts.selectedAgentId ?? "");
    const current = String(opts.currentAgentId ?? "");
    const taskRows = await ctx.fns.procs.db.select({ sql: "SELECT id, title, scratchpad, updated_at FROM agents WHERE archived_at IS NULL AND jsonb_exists(scratchpad::jsonb, 'sharedAgentTask') ORDER BY updated_at DESC LIMIT 20", params: [] }) as any[];
    const tasks = taskRows.map((row: any) => { let pad: any = row.scratchpad ?? {}; if (typeof pad === "string") { try { pad = JSON.parse(pad); } catch { pad = {}; } } const meta = pad.delegation ?? {}; return { id: String(row.id), title: String(row.title ?? ""), task: String(pad.sharedAgentTask?.task ?? ""), status: String(meta.status ?? "working"), summary: meta.summary == null ? "" : String(meta.summary), result: meta.result?.result ?? null, updatedAt: Number(row.updated_at ?? 0) }; });
    const field = "rounded-md border border-ui-border bg-base-100 px-3 py-2 text-xs outline-none focus:border-primary";
    const publish = `<section class="rounded-xl border border-ui-border bg-base-100 p-4 shadow-sm"><h2 class="text-sm font-semibold">Publish a session</h2><p class="mt-1 text-xs text-subtle">Expose its accumulated context through a small capability card. The transcript itself stays hidden.</p><form method="POST" action="/shared-agents/publish" class="mt-3 grid gap-3 md:grid-cols-2"><label class="grid gap-1 text-xs"><span>Session</span><select name="agentId" required class="${field}">${agents.map((item: any) => `<option value="${esc(item.id)}" ${item.id === current ? "selected" : ""}>${esc(item.title || item.id)} (${esc(item.id)})</option>`).join("")}</select></label><label class="grid gap-1 text-xs"><span>Registry name</span><input name="name" required maxlength="120" class="${field}" placeholder="Research reviewer"></label><label class="grid gap-1 text-xs md:col-span-2"><span>Description</span><textarea name="description" required rows="2" class="${field}" placeholder="What this session knows and which work it can do"></textarea></label><label class="grid gap-1 text-xs md:col-span-2"><span>Capabilities, comma-separated</span><input name="capabilities" required class="${field}" placeholder="literature review, evidence synthesis"></label><button class="justify-self-start rounded-md bg-primary px-4 py-2 text-xs font-medium text-primary-content">Publish</button></form></section>`;
    const registry = cards.length ? cards.map((card: any) => `<article class="rounded-xl border ${card.agentId === selected ? "border-primary ring-2 ring-primary/15" : "border-ui-border"} bg-base-100 p-4 shadow-sm"><div class="flex items-start gap-2"><i class="ph ph-brain text-lg text-primary"></i><div class="min-w-0 flex-1"><h3 class="font-semibold">${esc(card.name)}</h3><p class="font-mono text-3xs text-faint">${esc(card.agentId)}</p></div><form method="POST" action="/shared-agents/unpublish"><input type="hidden" name="agentId" value="${esc(card.agentId)}"><button title="Unpublish" class="text-faint hover:text-error"><i class="ph ph-x"></i></button></form></div><p class="mt-2 text-xs leading-5 text-muted">${esc(card.description)}</p><div class="mt-2 flex flex-wrap gap-1">${(card.capabilities ?? []).map((cap: string) => `<span class="rounded-full bg-base-200 px-2 py-0.5 text-3xs text-subtle">${esc(cap)}</span>`).join("")}</div><form method="POST" action="/shared-agents/delegate" class="mt-3 grid gap-2"><input type="hidden" name="agentId" value="${esc(card.agentId)}"><input type="hidden" name="requesterId" value="${esc(current)}"><textarea name="task" required rows="2" class="${field}" placeholder="Task for this context agent"></textarea><button class="justify-self-start rounded-md border border-primary/30 px-3 py-1.5 text-xs font-medium text-primary hover:bg-primary/10">Delegate task</button></form></article>`).join("") : '<div class="rounded-xl border border-dashed border-ui-border p-6 text-center text-sm text-faint">No published agents yet.</div>';
    const recent = tasks.length ? tasks.map((task: any) => `<article class="rounded-lg border border-ui-border bg-base-100 p-3"><div class="flex items-center gap-2"><a href="/agent/${encodeURIComponent(task.id)}" class="min-w-0 flex-1 truncate text-xs font-medium hover:text-primary">${esc(task.task || task.title)}</a><span class="rounded-full bg-base-200 px-2 py-0.5 text-3xs">${esc(task.status)}</span></div>${task.summary ? `<p class="mt-2 text-xs text-muted">${esc(task.summary)}</p>` : ""}${task.result != null ? `<pre class="mt-2 max-h-40 overflow-auto whitespace-pre-wrap rounded bg-base-200 p-2 text-3xs">${esc(typeof task.result === "string" ? task.result : JSON.stringify(task.result, null, 2))}</pre>` : ""}<div class="mt-1 text-3xs text-faint">${new Date(task.updatedAt).toLocaleString()}</div></article>`).join("") : '<p class="text-xs text-faint">No delegated tasks yet.</p>';
    return `<div class="mx-auto w-full max-w-7xl p-5 sm:p-8"><div class="mb-6"><h1 class="text-2xl font-semibold tracking-tight">Shared Agents</h1><p class="mt-1 text-sm text-subtle">Published sessions that other agents can discover and use for focused tasks.</p></div>${publish}<div class="mt-6 grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]"><section><h2 class="mb-3 text-sm font-semibold">Registry</h2><div class="grid gap-3 md:grid-cols-2">${registry}</div></section><section><h2 class="mb-3 text-sm font-semibold">Recent tasks</h2><div class="space-y-2">${recent}</div></section></div></div>`;
}
