/** GET /news — Hyper-native durable news reader and archive. */
export default async function(ctx:Context,_session:Session|null,opts:{req:Request;params:Record<string,string>}){
 const esc=(v:any)=>ctx.fns.procs.ui.escape({text:String(v??"")}),u=new URL(opts.req.url),q=(u.searchParams.get("q")??"").trim(),source=u.searchParams.get("source")??"",view=u.searchParams.get("view")??"unread",offset=Math.max(0,Number(u.searchParams.get("offset")??0));
 const [stats,sources,rows]=await Promise.all([ctx.fns.news.stats({}),ctx.fns.news.sources({}),ctx.fns.news.list({query:q||undefined,source:source||undefined,unread:view==='unread'?true:undefined,liked:view==='liked'?true:undefined,limit:30,offset})]);
 const href=(change:Record<string,string|number>)=>{const p=new URLSearchParams();const x={q,source,view,...change};for(const[k,v]of Object.entries(x))if(v!==""&&v!==0&&!(k==="view"&&v==="unread"))p.set(k,String(v));const s=p.toString();return s?`/news?${s}`:"/news"};
 const tabs=ctx.fns.procs.ui.tabs({current:view==="all"||view==="liked"?view:"unread",items:[["unread","Unread",stats.unread,"ph-circle"],["all","Archive",stats.total,"ph-archive"],["liked","Liked",stats.liked,"ph-heart"]].map(([key,label,n,icon])=>({value:String(key),label:String(label),count:Number(n),icon:String(icon),href:href({view:String(key),offset:0})}))});
 const chips=sources.map((s:any)=>`<a href="${href({source:s.source===source?"":s.source,offset:0})}" class="inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-2xs ${s.source===source?"border-primary bg-primary/10 text-primary":"border-base-300 hover:bg-base-200"}">${esc(s.label??s.source)} <b>${s.total}</b></a>`).join("");
 const cards=rows.map((r:any)=>{const date=new Date(r.shown_at??r.fetched_at).toISOString().slice(0,10),readerParams=new URLSearchParams({id:r.id,source,q,unread:view==='unread'?"1":"0"});return `<article class="border-t border-base-200 px-4 py-4 first:border-t-0 hover:bg-base-200/35"><div class="flex gap-3"><div class="flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-xs font-semibold text-primary">${esc(String(r.source_label??r.source).slice(0,2).toUpperCase())}</div><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2 text-2xs text-faint"><span class="font-medium text-subtle">${esc(r.source_label??r.source)}</span><span>·</span><time>${date}</time>${r.liked_at?`<i class="ph-fill ph-heart text-error"></i>`:""}${!r.read_at?`<span class="size-1.5 rounded-full bg-primary"></span>`:""}</div><a href="/news/reader?${readerParams}" class="mt-1 block text-base font-semibold leading-6 hover:text-primary">${esc(r.title)}</a>${r.image_url?`<img src="${esc(r.image_url)}" alt="" loading="lazy" class="mt-3 max-h-72 w-full rounded-xl object-cover">`:""}${r.summary?`<p class="mt-2 line-clamp-3 text-sm leading-6 text-subtle">${esc(r.summary)}</p>`:""}<div class="mt-3 flex items-center gap-3 text-xs text-faint">${r.points!=null?`<span><i class="ph ph-arrow-up"></i> ${r.points}</span>`:""}${r.comments!=null?`<span><i class="ph ph-chat-circle"></i> ${r.comments}</span>`:""}${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noreferrer" class="ml-auto text-primary hover:underline">Original <i class="ph ph-arrow-square-out"></i></a>`:""}</div></div></div></article>`}).join("");
 const sourceLabel=sources.find((s:any)=>s.source===source);
 const sourceFilter=await ctx.fns.ui.inplacePopup({id:"news-sources",
  triggerHtml:`<i class="ph ph-funnel" aria-hidden="true"></i><span class="max-w-[12rem] truncate">${esc(source?(sourceLabel?.label??source):"All sources")}</span><i class="ph ph-caret-down text-xs text-faint" aria-hidden="true"></i>`,
  triggerAttrs:'class="ui-button ui-button--sm '+(source?'ui-button--primary':'ui-button--default')+'" title="Filter by source" aria-label="Filter by source"',
  panelAttrs:'aria-label="Sources" style="width:min(24rem,calc(100vw - 2rem))"',
  contentHtml:`<div class="flex flex-wrap gap-1.5">${chips}</div>${source?`<a href="${href({source:"",offset:0})}" class="mt-3 block text-xs text-subtle hover:text-base-content">All sources</a>`:""}`});
 return {title:"News",main:`<div class="mx-auto w-full max-w-5xl p-5 sm:p-8" data-page="news"><header class="flex flex-wrap items-center justify-between gap-3"><h1 class="text-2xl font-semibold tracking-tight">News</h1><div class="flex flex-wrap items-center gap-2">${ctx.fns.procs.ui.button({action:"reader",html:`<i class="ph ph-presentation"></i><span>Reader</span><kbd class="kbd kbd-xs">J</kbd>`,href:`/news/reader?source=${encodeURIComponent(source)}&q=${encodeURIComponent(q)}&unread=${view==='unread'?1:0}`,tone:"default"})}</div></header><div class="mt-4 flex flex-wrap items-center gap-x-5 gap-y-3">${tabs}<div class="flex min-w-[16rem] flex-1 items-center gap-2"><form action="/news" method="GET" class="flex-1"><input type="hidden" name="view" value="${esc(view)}">${source?`<input type="hidden" name="source" value="${esc(source)}">`:""}<label class="relative block"><i class="ph ph-magnifying-glass absolute left-3 top-1/2 -translate-y-1/2 text-faint" aria-hidden="true"></i><input type="search" name="q" value="${esc(q)}" placeholder="Search the archive" aria-label="Search the archive" class="input input-sm w-full pl-9"></label></form>${sourceFilter}</div></div><section class="mt-4 overflow-hidden rounded-xl border border-base-300 bg-base-100 shadow-sm">${cards||`<div class="p-12 text-center text-sm text-faint">No stored stories match this view.</div>`}</section><div class="mt-4 flex justify-end gap-2">${offset?`<a href="${href({offset:Math.max(0,offset-30)})}" class="rounded-lg border border-base-300 px-3 py-2 text-xs">Newer</a>`:""}${rows.length===30?`<a href="${href({offset:offset+30})}" class="rounded-lg border border-base-300 px-3 py-2 text-xs">Older</a>`:""}</div></div>`};
}
