/**
 * Verifies a submitted CSRF token against the current signed session cookie
 *
 * Performs constant-time comparison of a submitted token with the cookie-bound token generated by auth.csrfToken. Use before every cookie-authenticated state-changing form action; it is independent of Origin and reverse-proxy hostnames.
 * @param opts.req Incoming state-changing request carrying the session cookie.
 * @param opts.token Submitted hidden form token.
 */
export default async function (
    ctx: Context,
    session: Session | null,
    opts: {
        /** Incoming state-changing request carrying the session cookie. */
        req: Request;
        /** Submitted hidden form token. */
        token: string;
    },
): Promise<boolean> {
    const { timingSafeEqual } = await import("node:crypto");
    const expected = await ctx.fns.auth.csrfToken({ req: opts.req });
    const actual = String(opts.token ?? "");
    if (!expected || actual.length !== expected.length) return false;
    const a = Buffer.from(actual);
    const b = Buffer.from(expected);
    return a.length === b.length && timingSafeEqual(a, b);
}
